
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

const SUPABASE_URL = "https://qpovabdidmnzxqexxbxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwb3ZhYmRpZG1uenhxZXh4YnhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MjI3NTIsImV4cCI6MjA1ODI5ODc1Mn0.8Eyt8ApnfQ9k8Rs3Kb751n1OGkEKlRS4PN2AhOi-SBo";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
    storageKey: 'supabase.auth.token',
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});
